version: "3"
services:
  tuapi-localTools:
    image: tuapi-localtools:latest
    build:
        context: .
        dockerfile: Dockerfile
    container_name: tuapi-localtools
    restart: unless-stopped
    ports:
      - "8081:8080"
    command: /opt/tools.out